# Generated by Django 3.1 on 2020-12-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_notes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='slug',
        ),
    ]
